### ISSUE TITLE
Thảo luận về ý tưởng dự án

### ISSUE THREAD

**Issue by Trang1936** [Trang1936/SE-FinalProject#1]

**Comment by leminhduong11026789** [comment]
Team mình có 2 hướng:
1: Làm web quảng cáo cho khu du lịch (tự đăng bài quảng cáo lên trang).
2: Làm web thi trắc nghiệm (các hình thức thi mở rộng so với hình thức thi truyền thống: Nối đáp án, sắp xếp đáp án, đề thi tự động trộn...)
Mọi người có ý kiến gì cứ đưa lên để thảo luận nhé =D

**Comment by khactoan** [comment]
Hiện tại thì T đang có ý tưởng xây dựng cái diễn đàn sinh viên trường HUS ☺ nhằm mục đích tạo ra một cộng đồng chia sẻ kiến thức, kinh nghiệm, và tổng hợp các đề thi của trường mình👆, ngoài ra có thể viết confession, gửi lời muốn nói, tặng nhạc hay thông báo các event của trg  :D :D :D ae thấy ý tưởng này sao ạ :P

**Comment by Trang1936** [comment]
Hay lắm =)) Ae học 4 năm rồi, để lại cho trường một ít gọi là kỉ niệm :D

**Comment by leminhduong11026789** [comment]
Thế mình chot cái nào thế cái diễn đàn ok đấy. Liệu nó có hơi hướng cổ không :D

**Comment by lamphuocthinh96** [comment]
T cũng nảy sinh suy nghĩ là làm 1 cái forum phong cách mới, chủ đề chưa nghĩ ra nhưng cái đó theo nhu cầu thì sẽ nhiều cần và thích 👯‍♂️

**Comment by nguyenngocanh610** [comment]
Thế là mình làm 1 kênh chia sẻ kiến thức , đề thi . Một kênh văn nghệ như bài hát quà tặng mỗi tuần. Một kênh confestion. còn j nữa không nhỉ?
 2 tháng có đủ không anh em

**Comment by Trang1936** [comment]
Cập nhật thông tin về trường có được không nhỉ? Chia sẻ suy nghĩ của cựu sinh viên, có nhiều quá không ae?

**Comment by leminhduong11026789** [comment]
Cập thế thế thì ai cập nhật. Hay cũng kiểu như bài đăng

**Comment by Trang1936** [comment]
Kiểu như vậy thôi a, mình có thể có cộng tác viên =))

**Comment by nguyenngocanh610** [comment]
Xong mình bán cho trường ✌️  ae sắp giàu rồi :D

**Comment by nguyenngocanh610** [comment]
Anh em xem chốt đi rồi đưa các đầu mục mong muốn + phải làm đi @@

**Comment by lamphuocthinh96** [comment]
Ai có hứng thì đăng nhập vào rồi đăng hỏi qua các topic. Rồi mọi người và thảo luận

**Comment by leminhduong11026789** [comment]
Giống nhóm face quá =D

**Comment by nguyenngocanh610** [comment]
uhm hầu như trên face nó có hết rồi

**Comment by nguyenngocanh610** [comment]
Không như kiểu phân chia thành nhiều nhóm diễn đàn theo các khoa của trg cũng hay

**Comment by lamphuocthinh96** [comment]
Face thì hay bị phân tâm bởi những cái khác, dễ bị trôi. Mình sẽ làm sao để nó thật độc đáo hơn =))

**Comment by Trang1936** [comment]
Giao diện hấp dẫn, bắt mắt này, kiểu khuynh hướng tình cảm học đường. Haha

**Comment by nguyenngocanh610** [comment]
thế mình làm luôn kiểu trang tư vấn & ghép cặp đôi cho các bạn sv luôn cho đủ bộ:v

**Comment by Trang1936** [comment]
Em gửi mail rồi nhé, càng nghĩ càng nảy sinh ra nhiều ý tưởng :3 có làm được hết hay không mới là chuyện quan trọng :p

**Comment by PVT961996** [comment]
Làm kiểu này cũng được. Vì còn có 2 tháng, nên aanh em tập trung vào những tính năng nổi bật nhé, còn lại mình có thể phát triển thêm :D

**Comment by nguyenbs** [comment]
Cái ý diễn đàn cũng không tồi, nhưng theo anh thì các em nên sử dụng một hệ thống mã nguồn mở có sẵn rồi sửa lại thì ổn hơn.
Hoặc là một mã nguồn PHP không cần mở, kiểu như XenForo.

Việc của bọn em sẽ là:
- Thiết kế nội dung
- Thiết kế theme
- Triển khai lên một máy chủ hosting miễn phí (anh sẽ hướng dẫn)
