### ISSUE TITLE
Lên ý tưởng và làm nội dung cho danh mục chia sẻ kiến thức

### ISSUE THREAD

**Issue by khactoan** [Trang1936/SE-FinalProject#10]

**Comment by leminhduong11026789** [comment]
Ý tưởng Kiến thức học tập
- Cho phép up ảnh đề thi các môn các năm, giữa kì, up lời giải nếu có.
- Tài liệu các môn.
- Kinh nghiệm thi cử trong từng môn
- Học thế nào cho phù hợp với sự giảng dạy của các giáo viên.
- Hỏi đáp cơ bản trong học tập
VD : học 2 môn thể dục 1 kì có được tính không, trượt môn này có thể thay bằng môn khác không ?.
Ý tưởng cho kiến thức khác ngoài học tập nghiên cứu (những kiến thức khác có thể để vào mục 'khác này').

**Comment by khactoan** [comment]
Ý tưởng khá hay và đẩy đủ đấy anh. A vào dky lại tài khoản để em cấp quyền admin và thực hiện những ý tưởng đã liệt kê nha. 🉑

**Comment by leminhduong11026789** [comment]
Anh tạo rồi nhé ! anh chắc phải chỉnh sửa nhiều đây ! nhìn không ưng mắt =D

**Comment by khactoan** [comment]
Em cấp quyền rồi nha. Giao diện thì tìm style nào đẹp rồi cài đặt vào sau đó customize chứ k phải mình code từ đầu
