### ISSUE TITLE
Customize Giao diện

### ISSUE THREAD

**Issue by lamphuocthinh96** [Trang1936/SE-FinalProject#13]
Download source code về và chạy, sửa giao diện

**Comment by lamphuocthinh96** [comment]
Host ftp://156.67.222.33
User: u567520563
Password: tpGGy3S5Luy0

Sau khi download source code copy vào thư mục htdoc
* Nếu chạy với database local thì cần phải install lại bằng cách tạo database cho web, thay đổi cấu hình trong library và xóa file install-lock.php trong thư mục internal_data. Sau đó chạy url localhost/xenforoFolder/install/index.php?install để cài đặt lại forum trên local

**Comment by khactoan** [comment]
Hôm qua t thử cài forum trên local, nhưng cái xampp nó đang bị lỗi access forbidden error 403. Mọi người tạo db bằng cách truy cập vào mysql của theo thông tin đã gửi, export ra rồi tạo db trên local để import file sql đấy vào. file sql này có dung lượng khá lớn nên phải cấu hình lại xampp, cụ thể là phải tăng cấu hình upload_max_filesize thì mới import được. Sau khi import db thì bắt đầu thử truy cập web bằng local xem thế nào nhé

**Comment by Trang1936** [comment]
Em thấy search trên mạng nó cũng hướng dẫn customize một số điểm. Mọi người thử search xem sao.

**Comment by khactoan** [comment]
Em thấy ở đâu thì post link lên cho mọi người xem

**Comment by lamphuocthinh96** [comment]
Toàn đã chạy đc DB trên local chưa. t import vào mà vẫn k đc. Dù đã đổi max_execute_time nó vẫn tự tắt đi. Nặng quá mà @@

**Comment by khactoan** [comment]
@lamphuocthinh96 import vào thì được rồi nhưng khi kết nối vẫn bị database error. mà cấu hình đúng hết k hiểu sao.

**Comment by khactoan** [comment]
Cơ mà lúc import có một số lỗi unicode, ông bị không

**Comment by lamphuocthinh96** [comment]
t chỉ import 1 lúc rồi nó bảo hết thời gian execute. đổi cái trong php.ini lên to lắm rồi vẫn chết. DB k đủ nên nó lỗi luôn

**Comment by leminhduong11026789** [comment]
trên admin mình có thể sửa một số file css ! Nhưng cấu trúc mình khó mà theo được ! Tình hình này team tập trung hơn cho nội dung. Nội dung hay thì tốt hơn.

**Comment by khactoan** [comment]
@lamphuocthinh96 t thì đổi xong import được nhưng vẫn bị lỗi một số dòng khi import unicode, nói chung vẫn chết db
@leminhduong11026789  đồng ý, xem có ý tưởng gì hay ho không, custom css trên cpanel của web luôn với lại so sánh với các forum khác xem mình còn thiếu những gì

**Comment by PVT961996** [comment]
Đã tích hợp thêm phát nhạc tự động trên nền web.

**Comment by khactoan** [comment]
@PVT961996 lần sau tích hợp cái gì thì tạo issue nha
