### ISSUE TITLE
Cập nhật chức năng quên mật khẩu.

### ISSUE THREAD

**Issue by Trang1936** [Trang1936/SE-FinalProject#14]
Quên mật khẩu trên forum đang bị lỗi.

**Comment by leminhduong11026789** [comment]
Hiện tại các hosting miễn phí sẽ không còn có thể dùng dịch vụ IMAP hoặc SMTP nữa. Vì thế chức năng gửi mail đang bị chặn.

**Comment by khactoan** [comment]
@leminhduong11026789  anh xem lại xem, cái bản trước em dùng host free vẫn gửi mail rầm rầm mà

**Comment by leminhduong11026789** [comment]
chỉnh sửa cấu hình trên admin nó thông báo đã gửi mail đi. Nhưng kiểm tra mail thì chưa có mail nào được gửi cả.

**Comment by khactoan** [comment]
Ok, để khi nào em xem lại xem, a nghiên cứu phần khác đi

**Comment by lamphuocthinh96** [comment]
Nó bảo đóng chức năng gửi mail của mấy host free rồi đó Toàn 
https://www.hostinger.vn/forum/tin-tuc-va-thong-bao/4585-ng%C6%B0ng-d%E1%BB%8Bch-v%E1%BB%A5-smtp-cho-free-ho.html

**Comment by khactoan** [comment]
![image](https://user-images.githubusercontent.com/20136759/34212459-eaa7e166-e5ce-11e7-804a-e8cf5f5ca5ef.png)
T vừa config gửi mail được rồi nhá, các thanh niên tìm hiểu chưa kỹ rồi. Host trên là host free của Hostinger nhưng cái host mình đang dùng thì chưa chắc đã bị chặn đâu

**Comment by khactoan** [comment]
Tuy nhiên thơi gian nhận mail hơi lâu, gần khoảng 20' sau mới nhận dk mail
