### ISSUE TITLE
Lỗi đăng nhập

### ISSUE THREAD

**Issue by lamphuocthinh96** [Trang1936/SE-FinalProject#15]
Khi nhập xong username và password và nhấn đăng nhập thì thấy load lại trang, không đăng nhập được và cũng không có thông báo lỗi

**Comment by lamphuocthinh96** [comment]
Lỗi này trong phần đăng nhập vào admin cũng bị, nhập đúng thì vẫn quay lại đăng nhập, nhập sai thì báo sai mật khẩu / tên, với tài khoản thường thì báo là không có quyền

**Comment by lamphuocthinh96** [comment]
@@ lỗi này do thằng chrome mình chặn cái gì đó làm nó cứ redirect lại trang đăng nhập. Dùng chrome or các trình duyệt khác thì ok.
Vậy nên issue này có thể close nhé!

**Comment by PVT961996** [comment]
Phải là dùng cốc cốc hoặc các trình duyệt khác thì mới ok chứ, chrome bị chặn.
