### ISSUE TITLE
Làm hiệu ứng tuyết rơi

### ISSUE THREAD

**Issue by lamphuocthinh96** [Trang1936/SE-FinalProject#16]
Tạo hiệu ứng tuyết trắng rơi trên màn hình của trang web, tạo không khí noel cho trang web

**Comment by lamphuocthinh96** [comment]
http://workshop.rs/2012/01/jquery-snow-falling-plugin/
Dựa trên hiệu ứng tuyết rơi tìm được trên google, cho phần plugin vào trong phần header của web

**Comment by khactoan** [comment]
Hay đó
