### ISSUE TITLE
Lên ý tưởng và làm nội dung cho danh mục media

### ISSUE THREAD

**Issue by khactoan** [Trang1936/SE-FinalProject#5]

**Comment by luongvinh1804** [comment]
Danh mục media sẽ bao gồm các đối tượng sau:
# 1, Tin tức chung
+, Tiểu luận, giải bóng đá, ngày hướng nghiệp, tuyển sinh và tuyển dụng,...
# 2, Tin tức sinh viên
+, Các cuộc thi liên quan đến sinh viên: lập trình, Rock Storm, cuộc thi Olympic, ....
+, Album ảnh: Kỉ yếu của sinh viên, hotgirl and hotboy của Hus, cuộc thi nữ sinh thanh lịch...
+, Thông tin tuyển dụng, việc làm cho sinh viên: Ngày hướng nghiệp, Thông tin việc làm từ các công ty ngoài, hội nghị khoa học,....
+, Điều cần biết: cách thức xin học bổng, phương pháp học tập trong đại học,....
# 3, Seminar
+, Seminar bộ môn Toán học và Tin học cấp trường, cấp quốc gia,... 
+, Các hội thảo quốc tế tổ chức tại trường,...
# 4, Cựu giáo chức
+, Các lễ kỉ niệm, các bài diễn thuyết của các thầy cô cựu giáo chức trong trường
+, Các bài viết của thầy cô 
+, Album ảnh quý của do các thầy cô cung cấp

**Comment by luongvinh1804** [comment]
Đó là ý tưởng định thực hiện là như vậy, mn xem đc chưa? vẫn còn có 1 xíu cần thắc mắc. @khactoan, lúc nào training cho t 1 xíu về code với,... c biết là t đã .... code r mà, :((
