### ISSUE TITLE
Lên ý tưởng và làm nội dung cho phần tin tức sự kiện 

### ISSUE THREAD

**Issue by khactoan** [Trang1936/SE-FinalProject#6]

**Comment by khactoan** [comment]
Ông làm luôn phần footer nha

**Comment by PVT961996** [comment]
ok

**Comment by PVT961996** [comment]
Tôi có chỉnh lại cái footer rồi đó, ông vào xem đã ok chưa?

**Comment by khactoan** [comment]
Ok rồi đó ông. Cái ảnh vẫn còn khung trắng xung quanh để tôi sửa nốt cho 👨‍🎨
