### ISSUE TITLE
Lên ý tưởng và làm nội dung cho danh mục tuyển sinh

### ISSUE THREAD

**Issue by khactoan** [Trang1936/SE-FinalProject#7]

**Comment by Trang1936** [comment]
Tuyển sinh thì mình sẽ chia làm 3 phần:
1. Tuyển sinh Đại học
2. Tuyển sinh trường chuyên Khoa Học Tự nhiên
3. Tuyển sinh sau đại học

**Comment by Trang1936** [comment]
Mỗi một chuyển mục sẽ có các phần:
1. Thông tin tuyển sinh mới nhất
2. Đề tuyển sinh qua các năm
3. Những gương mặt thủ khoa tiêu biểu

**Comment by khactoan** [comment]
Lên ý tưởng xong thì vào thực thi ở trên forum luôn (Tạo các category, forum như đã nêu và đăng nội dung). Khi nào thực thi xong mới close nhé

**Comment by Trang1936** [comment]
Okie. Cơ mà ý tưởng như vậy được chưa a? :D

**Comment by khactoan** [comment]
Ý tưởng okie rồi đó
