### ISSUE TITLE
Lên ý tưởng và làm nội dung cho danh mục Life style

### ISSUE THREAD

**Issue by khactoan** [Trang1936/SE-FinalProject#8]

**Comment by nguyenngocanh610** [comment]
- Có mục bài viết: cho phép đăng các bài viết về phong các sống: phong các sống giới trẻ, phong các sống của những người thành công, lối sống không tốt, lối sông đẹp.
- Có mục tạo động lực: đăng bài, chia sẻ các video tạo động lực, những videotruyền cảm hứng.
- Có mục tri thức của bạn: cho phép đăng các mẩu chuyện, cuốn sách, những chia sẻ qua những mẩu chuyên, cuốn sách hay.
- Có mục Phong cách thời trang: chia sẻ, đăng những phong cách thời trang, những phong cách ăn mặc: đường phố, đi chơi......
- Có mục du lịch: noi chia sẻ những địa điểm du lịch, kinh nghiệm đi phượt, review các địa điểm du lịch.
- Có mục chia sẻ thành công: chia sẻ những phong các sống, lỗi nghĩ, phong thái, suy nghĩ của những người thành công, chia sẻ những cuộc đời của những người thành công, chia sẻ các lối sống tốt để thành công trong cuộc sống.

**Comment by nguyenngocanh610** [comment]
Mọi người xem có thể bổ sung giúp xem ổn chưa, bố cục các mục đã ok chưa nhé.

**Comment by khactoan** [comment]
Mục bài viết và mục tạo động lực em thấy cần đổi tên lại vì nghe chưa hay lắm còn những mục dưới nghe ok phết. Đổi sang host mới nên chịvào dky lại tài khoản để em cấp quyền admin và thực hiện những ý tưởng đã liệt kê nha. 👍

**Comment by nguyenngocanh610** [comment]
không chị sẽ không để tên thế đâu, chỉ là nội dung mỗi lục nó sẻ kiểu thế.

**Comment by nguyenngocanh610** [comment]
Mọi ng có thể nghĩ tên giúp chị nhé :D

**Comment by khactoan** [comment]
Em cấp chị quyền admin rồi nha. C vào làm nội dung và thiết kế danh mục nhá
